app:
    resource: '@AppBundle/Controller/'
    type: annotation

#nelmio-api-doc:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /documentation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
